### ISSUE TITLE
Non-existent JSON file should not result in a crash

### ISSUE THREAD

**Issue by yizhang82** [Azure/service-fabric-mesh-preview#178]
Assuming a.json isn't present:

```
az mesh deployment create --resource-group abc --template-file a.json
If the deployment takes more than 10 minutes, then open up a new CLI window and run the following to get the status of your application deployment.
az mesh app show --resource-group <resource group name> --name <application name>
The output should point to the potential issue. If the “app show” cmd response does not have any errors listed, then it could just be that your image is taking long to download, rerun the az mesh app show command again after 5 minutes.
[Errno 2] No such file or directory: 'a.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 337, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 311, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 421, in default_command_handler
    result = op(**command_args)
  File "/home/yizhang82/.azure/cliextensions/mesh/azext_mesh/custom.py", line 260, in deploy_arm_template
    deployment_name, parameters, mode, no_wait=no_wait)
  File "/home/yizhang82/.azure/cliextensions/mesh/azext_mesh/custom.py", line 231, in _deploy_arm_template_core
    template = get_file_json(template_file, preserve_order=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 114, in get_file_json
    content = read_file_content(file_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 125, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'a.json'
```

The callstack here is more likely a crash rather than a correct error-handling. We should print out a graceful error message.

**Comment by VipulM-MSFT** [comment]
This is now fixed:

vipul@Azure:~$ az mesh deployment create -g vipumtest11 --template-file a.json
Deploying...
[Errno 2] No such file or directory: 'a.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
