### ISSUE TITLE
az mesh volume list --output table [Table output unavailable]

### ISSUE THREAD

**Issue by plooploops** [Azure/service-fabric-mesh-preview#191]
az mesh volume list is a workaround.
![image](https://user-images.githubusercontent.com/2498998/42118161-0df13028-7bb6-11e8-908f-e062fd86fb17.png)

**Comment by linggengmsft** [comment]
@abhishekram The table parsing is broken:

Traceback (most recent call last):
  File "/home/linggeng/depot/azure-cli/env/lib/python3.5/site-packages/knack/output.py", line 56, in format_table
    result = obj.table_transformer(result)
  File "/home/linggeng/.azure/devcliextensions/mesh/azext_mesh/commands.py", line 97, in transform_volume_list
    return [transform_volume(volume) for volume in result]
  File "/home/linggeng/.azure/devcliextensions/mesh/azext_mesh/commands.py", line 97, in <listcomp>
    return [transform_volume(volume) for volume in result]
  File "/home/linggeng/.azure/devcliextensions/mesh/azext_mesh/commands.py", line 92, in transform_volume
    ('Provider', result['properties']['provider'])])
KeyError: 'properties'

**Comment by wangcai0124** [comment]
This issue get fixed and it will be published while we release the next version of CLI.
