### ISSUE TITLE
Error deploying local cluster

### ISSUE THREAD

**Issue by aditmer** [Azure/service-fabric-mesh-preview#240]
Hello,

I'm getting the following error deploying a local cluster:

System.IO.IOException: The network path was not found.

   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
   at System.Fabric.FabricDeployer.Utility.GetTempPathInner(String machineName)
   at System.Fabric.FabricDeployer.Utility.GetTempPath(String machineName)

Repro:  I downloaded the Service Fabric Mesh Visual Studio tools and created a blank API app.  I tried to run it locally and VS failed to create the local cluster.  It recommended I create it through the Notification Center.  This also failed with the same error.

Thanks for your help.

**Comment by amanbha** [comment]
@maburlik could you help with this FabricDeployer error?
